version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  webserver:
    build: .
    container_name: airflow_webserver
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/purwadika-502e43f1636d.json
      - AIRFLOW__WEBSERVER__SECRET_KEY=ini_adalah_secret_key_yang_harus_panjang_dan_acak
    volumes:
      - ./airflow:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./cms_claims_dbt_project:/opt/airflow/cms_claims_dbt_project
      - ./purwadika-502e43f1636d.json:/opt/airflow/purwadika-502e43f1636d.json
      - C:\Users\NUR AYU LASMINI\.dbt\profiles.yml:/opt/airflow/.dbt/profiles.yml
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 5

  scheduler:
    build: .
    container_name: airflow_scheduler
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/airflow/purwadika-502e43f1636d.json
      - AIRFLOW__WEBSERVER__SECRET_KEY=ini_adalah_secret_key_yang_harus_panjang_dan_acak
    volumes:
      - ./airflow:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./cms_claims_dbt_project:/opt/airflow/cms_claims_dbt_project
      - ./purwadika-502e43f1636d.json:/opt/airflow/purwadika-502e43f1636d.json
      - C:\Users\NUR AYU LASMINI\.dbt\profiles.yml:/opt/airflow/.dbt/profiles.yml
    command: scheduler
    healthcheck:
      test: ["CMD-SHELL", "airflow jobs check --job-type SchedulerJob --hostname `hostname`"]
      interval: 30s
      timeout: 30s
      retries: 5