version: 2

models:
  - name: dim_patient
    description: "Dimension table for CMS beneficiaries/patients"
    columns:
      - name: beneficiary_id
        tests:
          - not_null
          - unique
      - name: gender
        tests:
          - not_null
          - accepted_values: { values: ['M', 'F', 'U'] }
  - name: dim_date
    description: "Dimension table for dates"
    columns:
      - name: date_key
        tests:
          - not_null
          - unique