name: 'purwadika'
version: '1.0.0'
config-version: 2

profile: 'purwadika'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  purwadika:
    +materialized: table
    staging:
      +materialized: view
      +schema: jcdeol005_capstone3_eko_staging
    dimensions:
      +schema: jcdeol005_capstone3_eko_model
      facts:
        +schema: jcdeol005_capstone3_eko_model
    